from Bai3_1.thuc_hien import tong_cac_ptu, chen, cong_cung_kich_thuoc ,xoa ,nhap_lieu
A = nhap_lieu("A")
B = nhap_lieu("B")
tA = tong_cac_ptu(A)
print(f"tong cua A la : ",tA)
tB = tong_cac_ptu(B)
print(f"tong cua A la : ",tB)
cA = chen(A,3,44)
print(f"sau khi chen vao A la : ",cA)
cB = chen(B,3,44)
print(f"sau khi chen vao A la : ",cB)
xA = xoa(A, 4)
print(f"sau khi xoa A la : ",xA)
xB = xoa(B, 4)
print(f"sau khi xoa A la : ",xB)
A_B = cong_cung_kich_thuoc(A,B)
print("sau khi A + B : ", A_B)